# Generated by Django 4.2.1 on 2023-05-24 21:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_alter_pic_emotion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pic',
            new_name='Image',
        ),
    ]
