# Generated by Django 4.2.8 on 2023-12-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_pic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
